### ISSUE TITLE
Wonderful Javascript chess engine!

### ISSUE THREAD

**Issue by kenpchess** [tomitank/tomitankChess#1]
Hello! Beautifully coded Javascript engine! I would love to see english translations for the comments in your source code.

And I know this is asking a lot, but I would also love to see a "stripped down" (minimal)
version that could be used for experimenting or code learning purposes.

Just one of the reasons I really like your code is I used to program (now retired) iin pascal
and various flavors of Basic and I just can not understand C++!

Anyway, thanks and great code!

- kenptest and kenpchess on various chess websites (kenpchess@gmail.com)

**Comment by tomitank** [comment]
Hi @kenpchess!

> Beautifully coded Javascript engine!
Thank you!

> I would love to see english translations for the comments in your source code.

In most cases, the names of variables and function will tell you everything.
Unfortunately, I have little time because I developing my mobile app.
Here you can download it:
https://apps.apple.com/us/app/sakk/id1150654415
https://play.google.com/store/apps/details?id=sakk.tanky.hu

> And I know this is asking a lot, but I would also love to see a "stripped down" (minimal)
> version that could be used for experimenting or code learning purposes.

the first version is based on garbochess.js and this youtube channel:
https://www.youtube.com/watch?v=2eA0bD3wV3Q&list=PLZ1QII7yudbe4gz2gh9BCI6VDA-xafLog

Best Regards,
Tamás

**Comment by huydhoang** [comment]
Not asking for anything here. I just want to say that this is the best JavaScript chess engine at the moment. It is very fast, faster than `lozza 2.0` per my testing, and obviously very strong ELO. Built in UCI interface and readable code. What could be better than that!
I'd like to perhaps improve the documentation. Would you welcome a pull request at some point?

**Comment by tomitank** [comment]
I look forward. If you like it, I push up
